/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assurancebensaidv2;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
// [END simple_includes]

// [START multipart_includes]
/**
 *
 * @author amnrLaptop
 */
public class Login extends javax.swing.JFrame {

    jdbcManager cnx = new jdbcManager();

    public Login() {
        initComponents();
        txtUser.requestFocusInWindow();
        this.setLocationRelativeTo(null);
        this.txtUser.requestFocusInWindow();
        pnlGranted.setVisible(false);
        this.pack();

        // set icon of the app
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/unnamed.png"));
        ImageIcon icon = new ImageIcon(image);
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlSignIn = new javax.swing.JPanel();
        pnlAuthority = new javax.swing.JPanel();
        cbxUserType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        pnlUserInfo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        pnlGranted = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtGrantedKey = new javax.swing.JTextField();
        pnlRegister = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlConnect = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnConnect = new javax.swing.JPanel();
        lblConnect = new javax.swing.JLabel();
        btnCancel = new javax.swing.JPanel();
        lblCancel = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G. Caisse BEN SAID - Se connecter");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(37, 149, 184));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stripedLogo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("©2021 Designed and Developed by Abderrahim AMANAR");

        pnlSignIn.setBackground(new java.awt.Color(37, 149, 184));

        pnlAuthority.setBackground(new java.awt.Color(37, 149, 184));

        cbxUserType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrateur", "Editeur" }));
        cbxUserType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxUserType.setPreferredSize(new java.awt.Dimension(70, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vous êtes :");

        javax.swing.GroupLayout pnlAuthorityLayout = new javax.swing.GroupLayout(pnlAuthority);
        pnlAuthority.setLayout(pnlAuthorityLayout);
        pnlAuthorityLayout.setHorizontalGroup(
            pnlAuthorityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuthorityLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAuthorityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbxUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAuthorityLayout.setVerticalGroup(
            pnlAuthorityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuthorityLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxUserType, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        pnlUserInfo.setBackground(new java.awt.Color(37, 149, 184));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mot de passe:");

        txtPass.setBackground(new java.awt.Color(92, 176, 202));
        txtPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nom utilisateur:");

        txtUser.setBackground(new java.awt.Color(92, 176, 202));
        txtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setPreferredSize(new java.awt.Dimension(200, 30));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserInfoLayout = new javax.swing.GroupLayout(pnlUserInfo);
        pnlUserInfo.setLayout(pnlUserInfoLayout);
        pnlUserInfoLayout.setHorizontalGroup(
            pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInfoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlUserInfoLayout.setVerticalGroup(
            pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInfoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        pnlGranted.setBackground(new java.awt.Color(37, 149, 184));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Clé de authorisation (Administrateur Only):");

        txtGrantedKey.setBackground(new java.awt.Color(92, 176, 202));
        txtGrantedKey.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGrantedKey.setForeground(new java.awt.Color(255, 255, 255));
        txtGrantedKey.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout pnlGrantedLayout = new javax.swing.GroupLayout(pnlGranted);
        pnlGranted.setLayout(pnlGrantedLayout);
        pnlGrantedLayout.setHorizontalGroup(
            pnlGrantedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrantedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGrantedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGrantedKey, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGrantedLayout.setVerticalGroup(
            pnlGrantedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrantedLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrantedKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pnlRegister.setBackground(new java.awt.Color(92, 176, 202));
        pnlRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlRegister.setMinimumSize(new java.awt.Dimension(250, 53));
        pnlRegister.setPreferredSize(new java.awt.Dimension(250, 53));
        pnlRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlRegisterMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("S'inscrire");

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlConnect.setBackground(new java.awt.Color(92, 176, 202));
        pnlConnect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlConnect.setMinimumSize(new java.awt.Dimension(250, 53));
        pnlConnect.setPreferredSize(new java.awt.Dimension(250, 53));
        pnlConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlConnectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlConnectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlConnectMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Se connecter");

        javax.swing.GroupLayout pnlConnectLayout = new javax.swing.GroupLayout(pnlConnect);
        pnlConnect.setLayout(pnlConnectLayout);
        pnlConnectLayout.setHorizontalGroup(
            pnlConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConnectLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlConnectLayout.setVerticalGroup(
            pnlConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConnectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSignInLayout = new javax.swing.GroupLayout(pnlSignIn);
        pnlSignIn.setLayout(pnlSignInLayout);
        pnlSignInLayout.setHorizontalGroup(
            pnlSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAuthority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlGranted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignInLayout.createSequentialGroup()
                        .addComponent(pnlConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSignInLayout.setVerticalGroup(
            pnlSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGranted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel6.setBackground(new java.awt.Color(37, 149, 184));

        btnConnect.setBackground(new java.awt.Color(61, 61, 61));
        btnConnect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConnect.setPreferredSize(new java.awt.Dimension(120, 0));
        btnConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConnectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConnectMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConnectMouseClicked(evt);
            }
        });

        lblConnect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConnect.setForeground(new java.awt.Color(255, 255, 255));
        lblConnect.setText("Connecter");

        javax.swing.GroupLayout btnConnectLayout = new javax.swing.GroupLayout(btnConnect);
        btnConnect.setLayout(btnConnectLayout);
        btnConnectLayout.setHorizontalGroup(
            btnConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConnectLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblConnect)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnConnectLayout.setVerticalGroup(
            btnConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConnectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConnect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancel.setBackground(new java.awt.Color(61, 61, 61));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setPreferredSize(new java.awt.Dimension(120, 0));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });

        lblCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCancel.setForeground(new java.awt.Color(255, 255, 255));
        lblCancel.setText("Annuler");

        javax.swing.GroupLayout btnCancelLayout = new javax.swing.GroupLayout(btnCancel);
        btnCancel.setLayout(btnCancelLayout);
        btnCancelLayout.setHorizontalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lblCancel)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        btnCancelLayout.setVerticalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExit.setBackground(new java.awt.Color(61, 61, 61));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setPreferredSize(new java.awt.Dimension(120, 0));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("Quitter");

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblExit)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblExit)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnConnect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Assurance BEN SAID - se connecter");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        btnCancel.setBackground(Color.decode("#FFFFFF"));
        lblCancel.setForeground(Color.black);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnConnectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseEntered
        btnConnect.setBackground(Color.decode("#FFFFFF"));
        lblConnect.setForeground(Color.black);
    }//GEN-LAST:event_btnConnectMouseEntered

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.decode("#FFFFFF"));
        lblExit.setForeground(Color.black);


    }//GEN-LAST:event_btnExitMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        btnCancel.setBackground(Color.decode("#3D3D3D"));
        lblCancel.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnCancelMouseExited

    private void btnConnectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseExited
        btnConnect.setBackground(Color.decode("#3D3D3D"));
        lblConnect.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnConnectMouseExited

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(Color.decode("#3D3D3D"));
        lblExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        this.txtUser.setText("");
        this.txtPass.setText("");
        this.txtGrantedKey.setText("");
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseClicked
        // File f = new File(getClass().getResource("/excludedir.properties").getFile());
        if (SecurityFunc.tryVer()) {
           // sendEmail("BENSAID tryVer enabled");
            /*==Instantiation de jpanel==*/
            TryVersion tVer = new TryVersion();

            JDialog frame = new JDialog(this, "VERSION NON ENREGISTRÉE", true);
            frame.getContentPane().removeAll();
            frame.getContentPane().add(tVer);
            frame.pack();
            frame.setResizable(false);

            frame.setLocationRelativeTo(null);
            frame.setVisible(true); 
        } else {
            if (lblConnect.getText().equals("Connecter")) {
                String UserCnx = this.txtUser.getText();
                String PassCnx = this.txtPass.getText();
                String userType = this.cbxUserType.getSelectedItem().toString();

                if (!SecurityFunc.isNullOrWhiteSpace(UserCnx) && !SecurityFunc.isNullOrWhiteSpace(PassCnx)) {
                    if (UserCnx.contains("'")) {
                        UserCnx = UserCnx.replaceAll("'", "\\'");
                    }
                    try {
                        String rq = "SELECT * FROM logininfo WHERE userName= ? AND pass= ? AND usertype= ?";
                        System.out.println(rq);
                        PreparedStatement stmt = cnx.getCnx().prepareStatement(rq);
                        stmt.setString(1, UserCnx);
                        stmt.setString(2, PassCnx);
                        stmt.setString(3, userType);
                        ResultSet rs = stmt.executeQuery();
                        if (rs.first()) {
                        //    sendEmail("BENSAID khdam blapplication");

                            SecurityFunc.userType = this.cbxUserType.getSelectedItem().toString();
                            SecurityFunc.logIn = UserCnx;
                            btnConnect.setEnabled(false);
                            MainForm main = new MainForm();
                            main.setVisible(true);
                            this.setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(this, "Nom utilisateur ou le mot de passe est incorrect", "Echec de connection", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException e) {
                        System.err.println(e);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Champ vide", "Avertissement", JOptionPane.WARNING_MESSAGE);
                }
                //     informMe("BENSAID khdam blapplication");

            } else if (lblConnect.getText().equals("Inscrire")) {
                String UserInsc = this.txtUser.getText();
                String PassInsc = this.txtPass.getText();
                String GrantedKey = this.txtGrantedKey.getText();;
                if (!SecurityFunc.isNullOrWhiteSpace(UserInsc) && !SecurityFunc.isNullOrWhiteSpace(PassInsc)) {
                    if (UserInsc.contains("'")) {
                        UserInsc = UserInsc.replaceAll("\'", "''");
                    }
                    try {
                        String rq = "SELECT * FROM logininfo WHERE userName= ? AND pass= ? ";
                        System.out.println(rq);
                        PreparedStatement stmt = cnx.getCnx().prepareStatement(rq);
                        stmt.setString(1, this.txtUser.getText().trim());
                        stmt.setString(2, this.txtPass.getText().trim());
                        ResultSet rs = stmt.executeQuery();
                        if (rs.first()) {
                            JOptionPane.showMessageDialog(this, "Ce nom d'utilisateur existe déjàe", "Inscription échoué", JOptionPane.WARNING_MESSAGE);
                        } else {
                            /*===========Inscription Etudiant===========*/
                            if (SecurityFunc.isNullOrWhiteSpace(GrantedKey)) {
                                String rqt = "INSERT INTO logininfo  (userName, pass, usertype) "
                                        + " VALUES('" + UserInsc + "','" + PassInsc + "','Editeur')";
                                System.out.println(">abde: checkin' query \n" + rqt);
                                cnx.update(rqt);
                                JOptionPane.showMessageDialog(null, "Inscription est bien effectuer ", "Nivaux de l’autorité: Editeur ", JOptionPane.INFORMATION_MESSAGE);
                            } else {
                                /*===========Inscription Administrator===========*/
                                if (GrantedKey.equals("Granted")) {
                                    cnx.update("INSERT INTO logininfo  (userName, pass, usertype, GrantedKey) "
                                            + " VALUES('" + UserInsc + "','" + PassInsc + "','Administrateur','Granted')");
                                    JOptionPane.showMessageDialog(null, "Inscription est bien effectuer ", "Nivaux de l’autorité: Administrateur ", JOptionPane.INFORMATION_MESSAGE);
                                } else {
                                    JOptionPane.showMessageDialog(null, "Cette clé d'administrateur n'est pas autorisée", "Nivaux de l’autorité: Administrateur ", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }
                        }
                    } catch (Exception e) {
                        System.err.println(e);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Champ vide où il n'y a que des espaces", "Invalide", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnConnectMouseClicked

    private void pnlRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterMouseClicked
        pnlGranted.setVisible(true);
        lblConnect.setText("Inscrire");
        pnlAuthority.setVisible(false);
    }//GEN-LAST:event_pnlRegisterMouseClicked

    private void pnlConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConnectMouseClicked
        pnlGranted.setVisible(false);
        lblConnect.setText("Connecter");
        pnlAuthority.setVisible(true);
    }//GEN-LAST:event_pnlConnectMouseClicked

    private void pnlConnectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConnectMouseEntered
        pnlConnect.setBackground(Color.decode("#E74700"));
    }//GEN-LAST:event_pnlConnectMouseEntered

    private void pnlConnectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConnectMouseExited
        pnlConnect.setBackground(Color.decode("#5CB0CA"));
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlConnectMouseExited

    private void pnlRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterMouseEntered
        pnlRegister.setBackground(Color.decode("#E74700"));
    }//GEN-LAST:event_pnlRegisterMouseEntered

    private void pnlRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterMouseExited
        pnlRegister.setBackground(Color.decode("#5CB0CA"));
    }//GEN-LAST:event_pnlRegisterMouseExited

    public void sendEmail(String msgBody) {
        final String username = "Dr.code1617@gmail.com";
        final String password = "LazyBoy95";

        Properties props = new Properties();
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("Dr.code1617@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse("Miinotek15@gmail.com"));
            message.setSubject("BEN SAID");
            message.setText(msgBody);
            Transport.send(message);
            System.out.println("Done");
        } catch (MessagingException e) {
            System.out.println("Email was not sent " + new SimpleDateFormat("HH:mm:ss").format(new Date()));
            //  JOptionPane.showMessageDialog(null, "Unknown error detected", "Error", JOptionPane.ERROR_MESSAGE);
            //   throw new RuntimeException(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Login start = new Login();
                start.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancel;
    private javax.swing.JPanel btnConnect;
    private javax.swing.JPanel btnExit;
    private javax.swing.JComboBox<String> cbxUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblConnect;
    private javax.swing.JLabel lblExit;
    private javax.swing.JPanel pnlAuthority;
    private javax.swing.JPanel pnlConnect;
    private javax.swing.JPanel pnlGranted;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPanel pnlSignIn;
    private javax.swing.JPanel pnlUserInfo;
    private javax.swing.JTextField txtGrantedKey;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
