package assurancebensaidv2;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author amnrLaptop
 */
public class MainForm extends javax.swing.JFrame {

    static JPanel activePanel;
    private final JPanel home = new PnlHome();
    private final JPanel clients = new PnlClients();
    private final JPanel Quit = new PnlQuitt();
    private final jdbcManager con = new jdbcManager();

    /**
     * Creates new form clients
     */
    public MainForm() {
        initComponents();
        HomeNavBarItem.setBackground(Color.decode("#E74700"));
        activePanel = home;
        display(home);
        setLocationRelativeTo(null);
        pack();
        lblNote.setVisible(false);
 
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/unnamed.png"));
        ImageIcon icon = new ImageIcon(image);
        setIconImage(icon.getImage());
    }

    public void display(JPanel panel) {
        pnlCardBase.removeAll();
        pnlCardBase.add(panel);
        pnlCardBase.repaint();
        pnlCardBase.revalidate();
        if (SecurityFunc.userType.equals("Administrateur")) {
            lblUserFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/levelASimple.png"))); // NOI18N
        } else if (SecurityFunc.userType.equals("Editeur")) {
            lblUserFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/levelESimple.png"))); // NOI18N
        }
        lblUser.setText(SecurityFunc.logIn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlNavBar = new javax.swing.JPanel();
        pnlProfile = new javax.swing.JPanel();
        pnlSetting = new javax.swing.JPanel();
        lblSetting = new javax.swing.JLabel();
        pnlUserInfo = new javax.swing.JPanel();
        lblUserFoto = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        pnlSmallSeparator = new javax.swing.JPanel();
        HomeNavBarItem = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cltVehNavBarItem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        QuittNavBarItem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmdPrintQ = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmdPrintC = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlBigSeparator = new javax.swing.JPanel();
        pnlCardBase = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmdIcon = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G. Caisse BEN SAID");
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setPreferredSize(new java.awt.Dimension(1100, 650));
        setSize(new java.awt.Dimension(1100, 650));

        pnlHeader.setBackground(new java.awt.Color(37, 149, 184));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mainLogoV2.png"))); // NOI18N

        pnlTitle.setBackground(new java.awt.Color(37, 149, 184));

        lblTitle.setFont(new java.awt.Font("Helvetica-Normal", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Système de GESTION DE CAISSE");

        jLabel1.setFont(new java.awt.Font("Helvetica-Normal", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 61, 61));
        jLabel1.setText("v1.0.19");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlNavBar.setBackground(new java.awt.Color(92, 176, 202));
        pnlNavBar.setMaximumSize(null);

        pnlProfile.setBackground(new java.awt.Color(92, 176, 202));

        pnlSetting.setBackground(new java.awt.Color(92, 176, 202));
        pnlSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSettingMouseExited(evt);
            }
        });

        lblSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/settingDisable smal.png"))); // NOI18N
        lblSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSettingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSettingLayout = new javax.swing.GroupLayout(pnlSetting);
        pnlSetting.setLayout(pnlSettingLayout);
        pnlSettingLayout.setHorizontalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        pnlSettingLayout.setVerticalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSettingLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblSetting)
                .addGap(8, 8, 8))
        );

        pnlUserInfo.setBackground(new java.awt.Color(92, 176, 202));
        pnlUserInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUserInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlUserInfoMouseReleased(evt);
            }
        });

        lblUserFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/levelASimple.png"))); // NOI18N

        lblUser.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        lblUser.setText("Abderrahm");

        javax.swing.GroupLayout pnlUserInfoLayout = new javax.swing.GroupLayout(pnlUserInfo);
        pnlUserInfo.setLayout(pnlUserInfoLayout);
        pnlUserInfoLayout.setHorizontalGroup(
            pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInfoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblUserFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlUserInfoLayout.setVerticalGroup(
            pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInfoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSmallSeparator.setBackground(new java.awt.Color(77, 102, 132));
        pnlSmallSeparator.setMaximumSize(new java.awt.Dimension(3, 0));
        pnlSmallSeparator.setMinimumSize(new java.awt.Dimension(3, 0));
        pnlSmallSeparator.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout pnlSmallSeparatorLayout = new javax.swing.GroupLayout(pnlSmallSeparator);
        pnlSmallSeparator.setLayout(pnlSmallSeparatorLayout);
        pnlSmallSeparatorLayout.setHorizontalGroup(
            pnlSmallSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        pnlSmallSeparatorLayout.setVerticalGroup(
            pnlSmallSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pnlSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlSmallSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlSmallSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlUserInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        HomeNavBarItem.setBackground(new java.awt.Color(92, 176, 202));
        HomeNavBarItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeNavBarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeNavBarItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeNavBarItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeNavBarItemMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica-Normal", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Accueil");

        javax.swing.GroupLayout HomeNavBarItemLayout = new javax.swing.GroupLayout(HomeNavBarItem);
        HomeNavBarItem.setLayout(HomeNavBarItemLayout);
        HomeNavBarItemLayout.setHorizontalGroup(
            HomeNavBarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeNavBarItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeNavBarItemLayout.setVerticalGroup(
            HomeNavBarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeNavBarItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cltVehNavBarItem.setBackground(new java.awt.Color(92, 176, 202));
        cltVehNavBarItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cltVehNavBarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cltVehNavBarItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cltVehNavBarItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cltVehNavBarItemMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica-Normal", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("clients et véhicules");

        javax.swing.GroupLayout cltVehNavBarItemLayout = new javax.swing.GroupLayout(cltVehNavBarItem);
        cltVehNavBarItem.setLayout(cltVehNavBarItemLayout);
        cltVehNavBarItemLayout.setHorizontalGroup(
            cltVehNavBarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cltVehNavBarItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cltVehNavBarItemLayout.setVerticalGroup(
            cltVehNavBarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cltVehNavBarItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        QuittNavBarItem.setBackground(new java.awt.Color(92, 176, 202));
        QuittNavBarItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuittNavBarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuittNavBarItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuittNavBarItemMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuittNavBarItemMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica-Normal", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quittance");

        javax.swing.GroupLayout QuittNavBarItemLayout = new javax.swing.GroupLayout(QuittNavBarItem);
        QuittNavBarItem.setLayout(QuittNavBarItemLayout);
        QuittNavBarItemLayout.setHorizontalGroup(
            QuittNavBarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuittNavBarItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuittNavBarItemLayout.setVerticalGroup(
            QuittNavBarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuittNavBarItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmdPrintQ.setBackground(new java.awt.Color(92, 176, 202));
        cmdPrintQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdPrintQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdPrintQMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdPrintQMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdPrintQMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica-Normal", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Imprimer quittance");

        javax.swing.GroupLayout cmdPrintQLayout = new javax.swing.GroupLayout(cmdPrintQ);
        cmdPrintQ.setLayout(cmdPrintQLayout);
        cmdPrintQLayout.setHorizontalGroup(
            cmdPrintQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmdPrintQLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cmdPrintQLayout.setVerticalGroup(
            cmdPrintQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmdPrintQLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmdPrintC.setBackground(new java.awt.Color(92, 176, 202));
        cmdPrintC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdPrintC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdPrintCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdPrintCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdPrintCMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica-Normal", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Imprimer crédit");

        javax.swing.GroupLayout cmdPrintCLayout = new javax.swing.GroupLayout(cmdPrintC);
        cmdPrintC.setLayout(cmdPrintCLayout);
        cmdPrintCLayout.setHorizontalGroup(
            cmdPrintCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmdPrintCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cmdPrintCLayout.setVerticalGroup(
            cmdPrintCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmdPrintCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlNavBarLayout = new javax.swing.GroupLayout(pnlNavBar);
        pnlNavBar.setLayout(pnlNavBarLayout);
        pnlNavBarLayout.setHorizontalGroup(
            pnlNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavBarLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(HomeNavBarItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cltVehNavBarItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuittNavBarItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdPrintC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cmdPrintQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNavBarLayout.setVerticalGroup(
            pnlNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavBarLayout.createSequentialGroup()
                .addGroup(pnlNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmdPrintQ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeNavBarItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cltVehNavBarItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuittNavBarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPrintC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBigSeparator.setBackground(new java.awt.Color(61, 61, 61));
        pnlBigSeparator.setMaximumSize(new java.awt.Dimension(0, 3));
        pnlBigSeparator.setMinimumSize(new java.awt.Dimension(0, 3));
        pnlBigSeparator.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlBigSeparatorLayout = new javax.swing.GroupLayout(pnlBigSeparator);
        pnlBigSeparator.setLayout(pnlBigSeparatorLayout);
        pnlBigSeparatorLayout.setHorizontalGroup(
            pnlBigSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBigSeparatorLayout.setVerticalGroup(
            pnlBigSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        pnlCardBase.setBackground(new java.awt.Color(255, 204, 153));
        pnlCardBase.setMinimumSize(new java.awt.Dimension(1000, 368));
        pnlCardBase.setPreferredSize(new java.awt.Dimension(1000, 368));
        pnlCardBase.setLayout(new java.awt.CardLayout());

        pnlFooter.setBackground(new java.awt.Color(92, 176, 202));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("©2017");

        cmdIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/infoIcon.png"))); // NOI18N
        cmdIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdIconMouseClicked(evt);
            }
        });

        lblNote.setBackground(new java.awt.Color(255, 255, 255));
        lblNote.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNote.setForeground(new java.awt.Color(255, 255, 255));
        lblNote.setText("Veuillez noter que si aucun véhicule n'est enregistré au client, le quittance ne sera pas affiché.");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cmdIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdIcon)
                    .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBigSeparator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
            .addComponent(pnlCardBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
            .addComponent(pnlNavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlNavBar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBigSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCardBase, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getAccessibleContext().setAccessibleName("Assurance BEN SAID");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSettingMouseEntered
        lblSetting.setIcon(new ImageIcon(getClass().getResource("/resources/settingActive smal.png")));
    }//GEN-LAST:event_pnlSettingMouseEntered

    private void pnlSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSettingMouseExited
        lblSetting.setIcon(new ImageIcon(getClass().getResource("/resources/settingDisable smal.png")));
    }//GEN-LAST:event_pnlSettingMouseExited

    private void pnlUserInfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUserInfoMouseReleased
        JMenuItem logOut = new JMenuItem("Se déconnecter");
        logOut.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                Login lf = new Login();
                lf.setVisible(true);
            }
        });

        if (SwingUtilities.isLeftMouseButton(evt)) {
            JPopupMenu m = new JPopupMenu();
            m.add(logOut);
            m.setPreferredSize(pnlUserInfo.getPreferredSize());
            Dimension size = pnlUserInfo.getPreferredSize();
            int x = (pnlUserInfo.getWidth() - size.width) / 2;
            int y = pnlUserInfo.getHeight();
            m.show(pnlUserInfo, x, y);
        }
    }//GEN-LAST:event_pnlUserInfoMouseReleased

    private void HomeNavBarItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeNavBarItemMouseEntered
        HomeNavBarItem.setBackground(Color.decode("#E74700"));
    }//GEN-LAST:event_HomeNavBarItemMouseEntered

    private void HomeNavBarItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeNavBarItemMouseExited
        if (!activePanel.equals(home)) {
            HomeNavBarItem.setBackground(Color.decode("#5CB0CA"));
        }
    }//GEN-LAST:event_HomeNavBarItemMouseExited

    private void cltVehNavBarItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cltVehNavBarItemMouseEntered
        cltVehNavBarItem.setBackground(Color.decode("#E74700"));
    }//GEN-LAST:event_cltVehNavBarItemMouseEntered

    private void QuittNavBarItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuittNavBarItemMouseEntered
        QuittNavBarItem.setBackground(Color.decode("#E74700"));
    }//GEN-LAST:event_QuittNavBarItemMouseEntered

    private void QuittNavBarItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuittNavBarItemMouseExited
        if (!activePanel.equals(Quit)) {
            QuittNavBarItem.setBackground(Color.decode("#5CB0CA"));
        }
    }//GEN-LAST:event_QuittNavBarItemMouseExited

    private void HomeNavBarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeNavBarItemMouseClicked
        if (!activePanel.equals(home)) {
            display(home);
            activePanel = home;
            HomeNavBarItem.setBackground(Color.decode("#E74700"));
            cltVehNavBarItem.setBackground(Color.decode("#5CB0CA"));
            QuittNavBarItem.setBackground(Color.decode("#5CB0CA"));
            lblNote.setVisible(false);
        }
        con.GeState();
    }//GEN-LAST:event_HomeNavBarItemMouseClicked

    private void cltVehNavBarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cltVehNavBarItemMouseClicked
        if (!activePanel.equals(clients)) {
            display(clients);
            activePanel = clients;
            HomeNavBarItem.setBackground(Color.decode("#5CB0CA"));
            cltVehNavBarItem.setBackground(Color.decode("#E74700"));
            QuittNavBarItem.setBackground(Color.decode("#5CB0CA"));
            lblNote.setVisible(false);
        }
    }//GEN-LAST:event_cltVehNavBarItemMouseClicked

    private void pnlSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSettingMouseClicked
        pnlSettings pnl = new pnlSettings();

        JDialog frame = new JDialog(this, "Paramètres", true);
        frame.setResizable(false);
        frame.getContentPane().removeAll();
        frame.getContentPane().add(pnl);
        frame.setSize(new Dimension(687, 300));

        frame.setLocationRelativeTo(this);
        frame.setVisible(true);    }//GEN-LAST:event_pnlSettingMouseClicked

    private void cltVehNavBarItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cltVehNavBarItemMouseExited
        if (!activePanel.equals(clients)) {
            cltVehNavBarItem.setBackground(Color.decode("#5CB0CA"));
        }
    }//GEN-LAST:event_cltVehNavBarItemMouseExited

    private void QuittNavBarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuittNavBarItemMouseClicked
        if (!activePanel.equals(Quit)) {
            display(Quit);
            activePanel = Quit;
            HomeNavBarItem.setBackground(Color.decode("#5CB0CA"));
            Quit.setBackground(Color.decode("#E74700"));
            cltVehNavBarItem.setBackground(Color.decode("#5CB0CA"));
            lblNote.setVisible(true);
        }
    }//GEN-LAST:event_QuittNavBarItemMouseClicked

    private void cmdIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdIconMouseClicked
        /*==Instantiation de jpanel==*/
        AboutFrame pnl = new AboutFrame();
        JDialog frame = new JDialog(this, "À propos", true);
        frame.setResizable(false);
        frame.getContentPane().removeAll();
        frame.getContentPane().add(pnl);
        frame.pack();

        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/unnamed.png"));
        ImageIcon icon = new ImageIcon(image);
        frame.setIconImage(icon.getImage());

        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }//GEN-LAST:event_cmdIconMouseClicked

    private void cmdPrintQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPrintQMouseClicked
        try {
            String repport = "C:/G. Caisse BEN SAID/report2.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(repport);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, jdbcManager.conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            javax.swing.JOptionPane.showMessageDialog(null, e.getMessage(), "Etat de L'opération", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdPrintQMouseClicked

    private void cmdPrintQMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPrintQMouseEntered
        cmdPrintQ.setBackground(Color.decode("#2595B8"));
    }//GEN-LAST:event_cmdPrintQMouseEntered

    private void cmdPrintQMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPrintQMouseExited
        cmdPrintQ.setBackground(Color.decode("#5CB0CA"));
    }//GEN-LAST:event_cmdPrintQMouseExited

    private void cmdPrintCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPrintCMouseClicked
        try {
            String repport = "C:/G. Caisse BEN SAID/report1.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(repport);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, jdbcManager.conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            javax.swing.JOptionPane.showMessageDialog(null, e.getMessage(), "Etat de L'opération", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdPrintCMouseClicked

    private void cmdPrintCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPrintCMouseEntered
        cmdPrintC.setBackground(Color.decode("#2595B8"));
    }//GEN-LAST:event_cmdPrintCMouseEntered

    private void cmdPrintCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPrintCMouseExited
        cmdPrintC.setBackground(Color.decode("#5CB0CA"));
    }//GEN-LAST:event_cmdPrintCMouseExited

    private void lblSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseClicked
        pnlSettings pnl = new pnlSettings();

        JDialog frame = new JDialog(this, "Paramètres", true);
        frame.setResizable(false);
        frame.getContentPane().removeAll();
        frame.getContentPane().add(pnl);
        frame.setSize(new Dimension(687, 300));

        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }//GEN-LAST:event_lblSettingMouseClicked

    private void lblSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseEntered
        lblSetting.setIcon(new ImageIcon(getClass().getResource("/resources/settingActive smal.png")));
    }//GEN-LAST:event_lblSettingMouseEntered

    private void lblSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseExited
        lblSetting.setIcon(new ImageIcon(getClass().getResource("/resources/settingDisable smal.png")));
    }//GEN-LAST:event_lblSettingMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainForm m = new MainForm();
                m.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeNavBarItem;
    private javax.swing.JPanel QuittNavBarItem;
    private javax.swing.JPanel cltVehNavBarItem;
    private javax.swing.JLabel cmdIcon;
    private javax.swing.JPanel cmdPrintC;
    private javax.swing.JPanel cmdPrintQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblSetting;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserFoto;
    private javax.swing.JPanel pnlBigSeparator;
    private javax.swing.JPanel pnlCardBase;
    public static javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlNavBar;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlSetting;
    private javax.swing.JPanel pnlSmallSeparator;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlUserInfo;
    // End of variables declaration//GEN-END:variables
}
