/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assurancebensaidv2;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amnrLaptop
 */
public class PnlHome extends javax.swing.JPanel {

    private final jdbcManager cnx;
    private Statement stm = null;
    private final DefaultTableModel homeModel = SecurityFunc.modelNoEditableCell();
    private final DefaultTableModel optModel = SecurityFunc.modelNoEditableCell();
    private final String[] tblHeader = {"CIN", "Nom complète", "Usage", "Date de Quittance",
        "Prime réelle", "Règlement", "Perte", "Crédit", "Decouper en:", "Type d'Attestation"};
    private final String[] optHeader = {"ID Opération", "Opération affecté", "Date d'opération", "Utilisateur", "Droit d'utilisateur"};
    private ResultSet rs;

    public PnlHome() {
        this.cnx = new jdbcManager();
        initComponents();
        SecurityFunc.setTable(homeModel, tblHeader, tblPricipale);
        SecurityFunc.setTable(optModel, optHeader, optTable);
        this.loadTable();
        cnx.GeState();
        this.loadOpt();
        linkOptRefrech.setToolTipText("Actualiser la table");
        linkQuittRefrech.setToolTipText("Actualiser la table");

//        pnlOpt.setVisible(false);
//        pnlQu.setVisible(false);
//        tblControle1.setVisible(false);
//        tblControle2.setVisible(false);
//        linkQuittRefrech.setVisible(false);
//        linkOptRefrech.setVisible(false);
//        iconC.setVisible(false);
//        iconP.setVisible(false);
//        iconPR.setVisible(false);
//        iconR.setVisible(false);
    }

    public final void loadTable() {
        try {
            //--------------------------------------------------------------------------------------
            String query = "SELECT c.cin, c.nomComplet, u.libaleUsage, q.dateQuitt, q.primeReele, q.reglement, q.perte, cr.creditSum, cr.Diviser, a.typeAttest "
                    + "FROM client c JOIN vehicle v ON c.cin = v.cin JOIN usages u ON v.idUsage = u.idUsage "
                    + "JOIN quittance q ON c.cin = q.cin JOIN fractionnement f ON q.numQuitt = f.numQuitt "
                    + "JOIN attestation a ON f.idAttest = a.idAttest JOIN credit cr ON q.numQuitt = cr.numQuitt ORDER BY q.dateQuitt LIMIT 20;";
            //--------------------------------------------------------------------------------------
            rs = cnx.select(query);
            homeModel.setRowCount(0);
            while (rs.next()) {
                homeModel.addRow(new Object[]{
                    rs.getString("cin"), rs.getString("nomComplet"),
                    rs.getString("libaleUsage"), rs.getDate("dateQuitt"),
                    rs.getFloat("primeReele"), rs.getFloat("reglement"),
                    rs.getFloat("perte"), rs.getFloat("creditSum"),
                    rs.getInt("Diviser"), rs.getString("typeAttest")
                });
            }
            SecurityFunc.resizeColumnWidth(tblPricipale);
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    public void loadOpt() {
        try {
            String q = "SELECT o.*,usertype FROM operation o JOIN logininfo log ON o.uName=log.userName ORDER BY o.dateOpt LIMIT 20;";
            rs = cnx.select(q);
            System.out.println(q);
            optModel.setRowCount(0);
            while (rs.next()) {
                optModel.addRow(new Object[]{
                    rs.getInt("idOpt"), rs.getString("libelOpt"),
                    rs.getString("dateOpt"), rs.getString("uName"),
                    rs.getString("usertype")
                });
            }
            SecurityFunc.resizeColumnWidth(optTable);
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        pnlStatistics = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        iconPR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        iconR = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        iconP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        iconC = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPricipale = new javax.swing.JTable();
        pnlQu = new javax.swing.JPanel();
        linkQuittRefrech = new javax.swing.JLabel();
        tblControle1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        optTable = new javax.swing.JTable();
        pnlOpt = new javax.swing.JPanel();
        linkOptRefrech = new javax.swing.JLabel();
        tblControle2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));

        pnlStatistics.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(39, 174, 96));
        jPanel6.setMaximumSize(new java.awt.Dimension(250, 140));
        jPanel6.setMinimumSize(new java.awt.Dimension(220, 140));
        jPanel6.setRequestFocusEnabled(false);

        lblPR.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblPR.setForeground(new java.awt.Color(255, 255, 255));
        lblPR.setText("pr");

        iconPR.setForeground(new java.awt.Color(255, 255, 255));
        iconPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/primeReeleIcon.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MAD");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prime Réelle");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconPR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblPR)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblPR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iconPR))
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel7.setBackground(new java.awt.Color(252, 87, 94));
        jPanel7.setMaximumSize(new java.awt.Dimension(250, 140));
        jPanel7.setMinimumSize(new java.awt.Dimension(220, 140));

        lblRglment.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblRglment.setForeground(new java.awt.Color(255, 255, 255));
        lblRglment.setText("reg");

        iconR.setForeground(new java.awt.Color(255, 255, 255));
        iconR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rglmentIcon.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MAD");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Règlement");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblRglment)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblRglment, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(iconR))
                .addGap(20, 20, 20))
        );

        jPanel8.setBackground(new java.awt.Color(20, 153, 211));
        jPanel8.setMaximumSize(new java.awt.Dimension(250, 140));
        jPanel8.setMinimumSize(new java.awt.Dimension(220, 140));

        lblP.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblP.setForeground(new java.awt.Color(255, 255, 255));
        lblP.setText("perte");

        iconP.setForeground(new java.awt.Color(255, 255, 255));
        iconP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/perteIcon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MAD");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Perte");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(lblP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(iconP))
                .addGap(20, 20, 20))
        );

        jPanel9.setBackground(new java.awt.Color(61, 61, 61));
        jPanel9.setMaximumSize(new java.awt.Dimension(250, 140));
        jPanel9.setMinimumSize(new java.awt.Dimension(220, 140));
        jPanel9.setPreferredSize(new java.awt.Dimension(220, 140));

        lblCredit.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblCredit.setForeground(new java.awt.Color(255, 255, 255));
        lblCredit.setText("credit");

        iconC.setForeground(new java.awt.Color(255, 255, 255));
        iconC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/creditIcon.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Credit");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MAD");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblCredit)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconC)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblCredit)))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout pnlStatisticsLayout = new javax.swing.GroupLayout(pnlStatistics);
        pnlStatistics.setLayout(pnlStatisticsLayout);
        pnlStatisticsLayout.setHorizontalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisticsLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        pnlStatisticsLayout.setVerticalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisticsLayout.createSequentialGroup()
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStatistics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnlStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(485, 200));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(485, 200));

        tblPricipale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblPricipale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPricipale.setRowHeight(20);
        tblPricipale.setSelectionForeground(java.awt.Color.black);
        jScrollPane1.setViewportView(tblPricipale);

        pnlQu.setBackground(new java.awt.Color(147, 38, 143));
        pnlQu.setMinimumSize(new java.awt.Dimension(100, 40));
        pnlQu.setPreferredSize(new java.awt.Dimension(0, 40));

        linkQuittRefrech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        linkQuittRefrech.setForeground(new java.awt.Color(255, 255, 255));
        linkQuittRefrech.setText("Les 20 quittances enregistrées");
        linkQuittRefrech.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkQuittRefrech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkQuittRefrechMouseClicked(evt);
            }
        });

        tblControle1.setForeground(new java.awt.Color(255, 255, 255));
        tblControle1.setText("Masquer");
        tblControle1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblControle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblControle1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlQuLayout = new javax.swing.GroupLayout(pnlQu);
        pnlQu.setLayout(pnlQuLayout);
        pnlQuLayout.setHorizontalGroup(
            pnlQuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(linkQuittRefrech)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tblControle1)
                .addContainerGap())
        );
        pnlQuLayout.setVerticalGroup(
            pnlQuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlQuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkQuittRefrech)
                    .addComponent(tblControle1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlQu, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlQu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(485, 200));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(485, 200));

        optTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        optTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        optTable.setRowHeight(20);
        optTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(optTable);

        pnlOpt.setBackground(new java.awt.Color(147, 38, 143));

        linkOptRefrech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        linkOptRefrech.setForeground(new java.awt.Color(255, 255, 255));
        linkOptRefrech.setText("Les 20 dernières opérations effectuées");
        linkOptRefrech.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkOptRefrech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkOptRefrechMouseClicked(evt);
            }
        });

        tblControle2.setForeground(new java.awt.Color(255, 255, 255));
        tblControle2.setText("Masquer");
        tblControle2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblControle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblControle2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlOptLayout = new javax.swing.GroupLayout(pnlOpt);
        pnlOpt.setLayout(pnlOptLayout);
        pnlOptLayout.setHorizontalGroup(
            pnlOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(linkOptRefrech)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tblControle2)
                .addContainerGap())
        );
        pnlOptLayout.setVerticalGroup(
            pnlOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkOptRefrech)
                    .addComponent(tblControle2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void linkOptRefrechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOptRefrechMouseClicked
        Timer blinkTimer = new Timer(500, new ActionListener() {
            private int count = 0;
            private int maxCount = 1;
            private boolean on = false;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (count >= maxCount) {
                    pnlOpt.setBackground(Color.decode("#93268F"));
                    ((Timer) e.getSource()).stop();
                } else {
                    pnlOpt.setBackground(Color.decode("#27AE60"));
                    on = !on;
                    count++;
                }
            }
        });
        blinkTimer.start();
        this.loadOpt();
    }//GEN-LAST:event_linkOptRefrechMouseClicked

    private void linkQuittRefrechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkQuittRefrechMouseClicked
        Timer blinkTimer = new Timer(500, new ActionListener() {
            private int count = 0;
            private int maxCount = 1;
            private boolean on = false;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (count >= maxCount) {
                    pnlQu.setBackground(Color.decode("#93268F"));
                    ((Timer) e.getSource()).stop();
                } else {
                    pnlQu.setBackground(Color.decode("#27AE60"));
                    on = !on;
                    count++;
                }
            }
        });
        blinkTimer.start();
        this.loadTable();
    }//GEN-LAST:event_linkQuittRefrechMouseClicked

    private void tblControle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblControle2MouseClicked
        if (tblControle2.getText().equals("Masquer")) {
            jScrollPane2.setVisible(false);
            tblControle2.setText("Afficher");
        } else if (tblControle2.getText().equals("Afficher")) {
            tblControle2.setText("Masquer");
            jScrollPane2.setVisible(true);
        }
    }//GEN-LAST:event_tblControle2MouseClicked

    private void tblControle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblControle1MouseClicked
        if (tblControle1.getText().equals("Masquer")) {
            jScrollPane1.setVisible(false);
            tblControle1.setText("Afficher");
        } else if (tblControle1.getText().equals("Afficher")) {
            tblControle1.setText("Masquer");
            jScrollPane1.setVisible(true);
        }
    }//GEN-LAST:event_tblControle1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconC;
    private javax.swing.JLabel iconP;
    private javax.swing.JLabel iconPR;
    private javax.swing.JLabel iconR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static final javax.swing.JLabel lblCredit = new javax.swing.JLabel();
    public static final javax.swing.JLabel lblP = new javax.swing.JLabel();
    public static final javax.swing.JLabel lblPR = new javax.swing.JLabel();
    public static final javax.swing.JLabel lblRglment = new javax.swing.JLabel();
    private javax.swing.JLabel linkOptRefrech;
    private javax.swing.JLabel linkQuittRefrech;
    private javax.swing.JTable optTable;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlOpt;
    private javax.swing.JPanel pnlQu;
    private javax.swing.JPanel pnlStatistics;
    private javax.swing.JLabel tblControle1;
    private javax.swing.JLabel tblControle2;
    private javax.swing.JTable tblPricipale;
    // End of variables declaration//GEN-END:variables

}
