package assurancebensaidv2;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author amnrLaptop
 */
public class pnlSettings extends javax.swing.JPanel {

    private JFileChooser fc;
    private SimpleDateFormat sdf;
    private String date;
    private String path;
    private String filename;
    private Process p = null;

    public pnlSettings() {
        initComponents();
        fc = new JFileChooser();
        sdf = new SimpleDateFormat("yyyy-MM-dd");
        cmdBuckup.setVisible(false);
        cmdRestore.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBrowse = new javax.swing.JTextField();
        cmdBrowse = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmdBuckup = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmdRestore = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbxOpt = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(231, 71, 0));

        txtBrowse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBrowse.setPreferredSize(new java.awt.Dimension(20, 20));

        cmdBrowse.setBackground(new java.awt.Color(61, 61, 61));
        cmdBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdBrowse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdBrowseMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Parcourir");

        javax.swing.GroupLayout cmdBrowseLayout = new javax.swing.GroupLayout(cmdBrowse);
        cmdBrowse.setLayout(cmdBrowseLayout);
        cmdBrowseLayout.setHorizontalGroup(
            cmdBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmdBrowseLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        cmdBrowseLayout.setVerticalGroup(
            cmdBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cmdBrowseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel5.setBackground(new java.awt.Color(37, 149, 184));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ici vous pouvez sauvegarder toutes vos données ou le restaurer");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Paramètres");

        cmdBuckup.setBackground(new java.awt.Color(77, 102, 132));
        cmdBuckup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdBuckup.setMaximumSize(new java.awt.Dimension(145, 39));
        cmdBuckup.setMinimumSize(new java.awt.Dimension(145, 39));
        cmdBuckup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdBuckupMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sauvegarde");

        javax.swing.GroupLayout cmdBuckupLayout = new javax.swing.GroupLayout(cmdBuckup);
        cmdBuckup.setLayout(cmdBuckupLayout);
        cmdBuckupLayout.setHorizontalGroup(
            cmdBuckupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmdBuckupLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        cmdBuckupLayout.setVerticalGroup(
            cmdBuckupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmdBuckupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmdRestore.setBackground(new java.awt.Color(77, 102, 132));
        cmdRestore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdRestore.setMaximumSize(new java.awt.Dimension(145, 39));
        cmdRestore.setMinimumSize(new java.awt.Dimension(145, 39));
        cmdRestore.setPreferredSize(new java.awt.Dimension(145, 39));
        cmdRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdRestoreMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Restaurer");

        javax.swing.GroupLayout cmdRestoreLayout = new javax.swing.GroupLayout(cmdRestore);
        cmdRestore.setLayout(cmdRestoreLayout);
        cmdRestoreLayout.setHorizontalGroup(
            cmdRestoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmdRestoreLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        cmdRestoreLayout.setVerticalGroup(
            cmdRestoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmdRestoreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbxOpt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxOpt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "******", "Sauvegarde", "Restaurer" }));
        cbxOpt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxOptItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmdBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbxOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdBuckup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdRestore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(cbxOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdBrowse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmdBuckup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdRestore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBrowseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdBrowseMouseClicked
        String item = this.cbxOpt.getSelectedItem().toString();
        if (item.equals("Sauvegarde")) {
            fc.showOpenDialog(this);
            date = sdf.format(new Date());
            try {
                File f = fc.getSelectedFile();
                if (f != null) {
                    path = f.getAbsolutePath();
                    path = path.replace('\\', '/');
                    path = path + "_" + date + ".sql";
                    txtBrowse.setText(path);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (item.equals("Restaurer")) {
            fc.showOpenDialog(this);
            try {
                File f = fc.getSelectedFile();
                if (f != null) {
                    path = f.getAbsolutePath();
                    path = path.replace('\\', '/');
                    txtBrowse.setText(path);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "choisir une option", "Aucune option choisie", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdBrowseMouseClicked

    private void cmdBuckupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdBuckupMouseClicked
        try {
            Runtime runtime = Runtime.getRuntime();
            p = runtime.exec("C:/wamp64/bin/mysql/mysql5.7.14/bin/mysqldump.exe -uroot -p12345 --add-drop-database -B AgenceAssurance -r" + path);
            int processComplete = p.waitFor();
            if (processComplete == 0) {
                JOptionPane.showMessageDialog(null, "Vos données ont été sauvegardées avec succès", "Sauvegarde", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Opération a ete échoué", "Echoué", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | IOException | InterruptedException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_cmdBuckupMouseClicked

    private void cmdRestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdRestoreMouseClicked
        String dbUserName = "root";// username
        String dbPassword = "12345";//Password
        String[] restoreCmd = new String[]{"C:/wamp64/bin/mysql/mysql5.7.14/bin/mysql.exe ", "--user=" + dbUserName, "--password=" + dbPassword, "-e", "source " + path};
        Process runtimProcess;
        try {
            runtimProcess = Runtime.getRuntime().exec(restoreCmd);
            int proceCom = runtimProcess.waitFor();
            if (proceCom == 0) {
                JOptionPane.showMessageDialog(null, "La récupération de données a été effectuée avec succès.\nRedémarrez votre application.", "Restauration", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Opération a ete échoué", "Echoué", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmdRestoreMouseClicked

    private void cbxOptItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxOptItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String item = this.cbxOpt.getSelectedItem().toString();
            if (item.equals("Restaurer")) {
                cmdRestore.setVisible(true);
                cmdBuckup.setVisible(false);

            } else if (item.equals("Sauvegarde")) {
                cmdBuckup.setVisible(true);
                cmdRestore.setVisible(false);

            } else {
                cmdBuckup.setVisible(false);
                cmdRestore.setVisible(false);
            }
        }
    }//GEN-LAST:event_cbxOptItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxOpt;
    private javax.swing.JPanel cmdBrowse;
    private javax.swing.JPanel cmdBuckup;
    private javax.swing.JPanel cmdRestore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBrowse;
    // End of variables declaration//GEN-END:variables
}
